export const siteConfig = {
  name: "Aniket Das - Full Stack Dev",
  authorName: "Aniket Das",
  username: "HackMEAny",
  description:
    "Aniket Das - Applied AI Engineer working at the intersection of AI, data, and scalable software systems. Explore my projects, experience, and contributions in software development and AI.",
  url: "https://www.anik3t.dev",
  links: {
    twitter: "https://x.com/Aniket10702843",
    github: "https://github.com/hackmeany",
    templateRepo: "",
  },
  ogImage: "",
  iconIco: "",
  logoIcon: "",
  keywords: [
    "Aniket Das",
    "Full Stack Developer",
    "AI Engineer",
    "Software Engineer",
    "Full Stack Developer",
    "Machine Learning",
    "Data Engineering",
    "UBS",
    "Python Developer",
    "React Developer",
    "Next.js Developer",
    "TypeScript",
    "Databricks",
    "AI Startups",
    "Software Development",
    "Web Developer",
    "Backend Developer",
    "Frontend Developer",
    "Tech Portfolio",
  ],
};
